/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inicio_sesion;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prg.Conexion;

/**
 *
 * @author User
 */
public class Usuarios extends javax.swing.JFrame {

    Conexion conexion;
    int ban = 0;
    ResultSet rs;
    Statement st;

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {

        initComponents();
        conexion = Conexion.getInstanciaConexion();
        conexion.openConnection();
        cargar_tabla();
        setTitle("GESTIONAR USUARIOS");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla_usuario = new javax.swing.JTable();
        txt_contraseña = new javax.swing.JTextField();
        txt_codigo_usuario = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        bt_eliminar = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_nuevo = new javax.swing.JButton();
        bt_volver = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6476-verde.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jcMousePanel1.add(jLabel1);
        jLabel1.setBounds(40, 90, 50, 16);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jcMousePanel1.add(jLabel2);
        jLabel2.setBounds(30, 150, 66, 15);

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo:");
        jcMousePanel1.add(jLabel3);
        jLabel3.setBounds(50, 40, 50, 15);

        tbl_tabla_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "USUARIO", "CONTRASEÑA"
            }
        ));
        tbl_tabla_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tabla_usuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tabla_usuario);

        jcMousePanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 190, 670, 160);

        txt_contraseña.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txt_contraseña.setEnabled(false);
        txt_contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contraseñaKeyPressed(evt);
            }
        });
        jcMousePanel1.add(txt_contraseña);
        txt_contraseña.setBounds(110, 140, 190, 40);

        txt_codigo_usuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txt_codigo_usuario.setEnabled(false);
        txt_codigo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo_usuarioActionPerformed(evt);
            }
        });
        jcMousePanel1.add(txt_codigo_usuario);
        txt_codigo_usuario.setBounds(110, 30, 60, 40);

        txt_usuario.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txt_usuario.setEnabled(false);
        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyPressed(evt);
            }
        });
        jcMousePanel1.add(txt_usuario);
        txt_usuario.setBounds(110, 80, 190, 40);

        bt_eliminar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        bt_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Eliminar.png"))); // NOI18N
        bt_eliminar.setText("ELIMINAR");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });
        jcMousePanel1.add(bt_eliminar);
        bt_eliminar.setBounds(140, 380, 120, 50);

        bt_guardar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        bt_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.png"))); // NOI18N
        bt_guardar.setText("GUARDAR");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });
        jcMousePanel1.add(bt_guardar);
        bt_guardar.setBounds(410, 380, 140, 50);

        bt_cancelar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        bt_cancelar.setText("CANCELAR");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });
        jcMousePanel1.add(bt_cancelar);
        bt_cancelar.setBounds(270, 380, 130, 50);

        bt_nuevo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        bt_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuevo.png"))); // NOI18N
        bt_nuevo.setText("NUEVO");
        bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevoActionPerformed(evt);
            }
        });
        jcMousePanel1.add(bt_nuevo);
        bt_nuevo.setBounds(20, 380, 110, 50);

        bt_volver.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        bt_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atrasss.png"))); // NOI18N
        bt_volver.setText("SALIR");
        bt_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_volverActionPerformed(evt);
            }
        });
        jcMousePanel1.add(bt_volver);
        bt_volver.setBounds(560, 380, 130, 50);

        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(0, 0, 710, 530);

        setBounds(0, 0, 717, 493);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo_usuarioActionPerformed

    private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed
        bt_cancelar.doClick();
        Conexion.getInstanciaConexion().deshabilitar_btn2(bt_nuevo, bt_eliminar, bt_guardar);
        Conexion.getInstanciaConexion().autonumerico("idusuario", "usuarios", txt_codigo_usuario);
        txt_usuario.setEnabled(true);
        txt_usuario.requestFocus();
        ban = 1;
    }//GEN-LAST:event_bt_nuevoActionPerformed

    private void txt_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_contraseña.requestFocus();
            txt_contraseña.setEnabled(true);
        }
    }//GEN-LAST:event_txt_usuarioKeyPressed

    private void txt_contraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contraseñaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bt_guardar.setEnabled(true);
            bt_guardar.requestFocus();
            bt_guardar.doClick();
        }
    }//GEN-LAST:event_txt_contraseñaKeyPressed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        if (txt_usuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la ciudad", "Atencion!!", JOptionPane.WARNING_MESSAGE);
            txt_usuario.requestFocus();
            return;
        }
        if (txt_contraseña.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la ciudad", "Atencion!!", JOptionPane.WARNING_MESSAGE);
            txt_contraseña.requestFocus();
            return;
        }
        int sms = JOptionPane.showConfirmDialog(null, "¿Desea grabar", "Grabar", JOptionPane.YES_NO_OPTION);
        if (sms == 0) {
            if (ban == 1) {
                try {
                    if (Conexion.
                            getInstanciaConexion().
                            obtenerRutaConeccion().
                            getAutoCommit()) {

                        Conexion.getInstanciaConexion().
                                obtenerRutaConeccion().
                                setAutoCommit(false);
                    }
                    PreparedStatement p = Conexion.getInstanciaConexion().
                            obtenerRutaConeccion().
                            prepareStatement("INSERT INTO usuarios(\n"
                                    + "	idusuario,usuario,contraseña)\n"
                                    + "	VALUES (?, ?, ?);");
                    p.setInt(1, Integer.parseInt(txt_codigo_usuario.getText()));
                    p.setString(2, (txt_usuario.getText()));
                    p.setString(3, (txt_contraseña.getText()));
                    p.executeUpdate();
                    Conexion.getInstanciaConexion().obtenerRutaConeccion().commit();
                    cargar_tabla();
                    bt_cancelar.doClick();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al grabar nuevo registro" + e);
                    deshacertransaccion();
                }
            }
        }
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        if (txt_codigo_usuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
            return;
        }
        int sms = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro seleccionar?",
                "Atencion!!!", JOptionPane.YES_NO_OPTION);
        if (sms == 0) {
            try {
                if (Conexion.
                        getInstanciaConexion().
                        obtenerRutaConeccion().
                        getAutoCommit()) {
                    Conexion.getInstanciaConexion().obtenerRutaConeccion().setAutoCommit(false);
                }

                PreparedStatement pe = Conexion.getInstanciaConexion().
                        obtenerRutaConeccion().
                        prepareStatement("delete from usuarios "
                                + " where idusuario=?");
                pe.setInt(1, Integer.parseInt(txt_codigo_usuario.getText()));
                pe.execute();
                Conexion.getInstanciaConexion().obtenerRutaConeccion().commit();
                cargar_tabla();
                bt_cancelar.doClick();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Debe seleccionar un registro" + e);
            }
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void tbl_tabla_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tabla_usuarioMouseClicked
        if (ban == 0) {
            String vcod = tbl_tabla_usuario.getValueAt(tbl_tabla_usuario.getSelectedRow(), 0).toString();
            recuperar_usuario(vcod);
        }
    }//GEN-LAST:event_tbl_tabla_usuarioMouseClicked

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        ban = 0;
        Conexion.getInstanciaConexion().habilitar_btn2(bt_nuevo, bt_eliminar, bt_guardar);
        txt_codigo_usuario.setText("");
        txt_usuario.setText("");
        txt_contraseña.setText("");
        txt_contraseña.setEnabled(false);
        txt_usuario.setEnabled(false);
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_volverActionPerformed
        dispose();

    }//GEN-LAST:event_bt_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_nuevo;
    private javax.swing.JButton bt_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTable tbl_tabla_usuario;
    private javax.swing.JTextField txt_codigo_usuario;
    private javax.swing.JTextField txt_contraseña;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {
        DefaultTableModel tab = (DefaultTableModel) tbl_tabla_usuario.getModel();
        tab.setRowCount(0);
        try {
            Conexion.getInstanciaConexion().listar_datos("select * from usuarios ");
            while (Conexion.getInstanciaConexion().rt.next()) {
                tab.addRow(new Object[]{
                    Conexion.getInstanciaConexion().rt.getString("idusuario"),
                    Conexion.getInstanciaConexion().rt.getString("usuario"),
                    Conexion.getInstanciaConexion().rt.getString("contraseña")});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla" + e);
        }
    }

    private void deshacertransaccion() {
        try {
            Conexion.getInstanciaConexion().obtenerRutaConeccion().rollback();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla" + e);
        }
    }

    private void recuperar_usuario(String vcod) {
        try {
            st = Conexion.getInstanciaConexion().obtenerRutaConeccion().createStatement();
            rs = st.executeQuery("SELECT idusuario, usuario, contraseña\n"
                    + "	FROM usuarios"
                    + " where idusuario=" + vcod);
            if (rs.next()) {
                txt_codigo_usuario.setText(rs.getString("idusuario"));
                txt_usuario.setText(rs.getString("usuario"));
                txt_contraseña.setText(rs.getString("contraseña"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar usuario" + e);
        }
    }
}
