/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario_Facturacion_Presupuesto;

import prg.Conexion;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class busca_productos extends java.awt.Dialog {

    Conexion conexion;
    public static int ban = 0;
    ResultSet rs;
    Statement st;

    public busca_productos(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
       conexion = Conexion.getInstanciaConexion();
        conexion.openConnection();
        setTitle("Busqueda de productos");
        Conexion conexion = new Conexion();
        cargar_tabla();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabla = new javax.swing.JTable();
        txt_buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6496-verde.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        tbl_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "COD. BARRAS", "DESCRIPCION", "PRECIO VENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_tabla);

        jcMousePanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 920, 390);

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        jcMousePanel1.add(txt_buscar);
        txt_buscar.setBounds(170, 40, 230, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BUSCAR:");
        jcMousePanel1.add(jLabel1);
        jLabel1.setBounds(80, 50, 64, 17);

        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jcMousePanel1.add(jButton1);
        jButton1.setBounds(420, 50, 130, 25);

        add(jcMousePanel1);
        jcMousePanel1.setBounds(-20, 0, 1130, 570);

        setSize(new java.awt.Dimension(970, 529));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog

    }//GEN-LAST:event_closeDialog

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        cargar_tabla();
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conexion.closeConnection();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                busca_productos dialog = new busca_productos(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTable tbl_tabla;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {
        DefaultTableModel tab = (DefaultTableModel) tbl_tabla.getModel();
        tab.setRowCount(0);
        try {
            st = Conexion.getInstanciaConexion().
                    obtenerRutaConeccion().createStatement();
            rs = st.executeQuery("select * from productos\n"
                    + "where (cod_barras::text ilike '%" + txt_buscar.getText() + "%'"
                    + " or  descripcion ilike '%" + txt_buscar.getText() + "%') order by descripcion asc ");
            while (rs.next()) {
                tab.addRow(new Object[]{
                    rs.getInt("idproducto"),
                    rs.getString("cod_barras"),
                    rs.getString("descripcion"),
                    rs.getString("precio_venta"),});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla" + e);
        }

    }
}
