/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inventario_Facturacion_Presupuesto;

import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prg.Conexion;

/**
 *
 * @author User
 */
public class reporte_balance_caja extends javax.swing.JFrame {

    Conexion conexion;
    public static int ban = 0;
    ResultSet rs;
    Statement st;
    SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form reporte_balance_caja
     */
    public reporte_balance_caja() {

        initComponents();
        conexion = Conexion.getInstanciaConexion();
        conexion.openConnection();
        setTitle("Balance de caja");
        this.setLocationRelativeTo(null);
        Conexion.getInstanciaConexion().obtenerRutaConeccion();
        cargar_tabla();
        Conexion conexion = new Conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_balance_caja = new javax.swing.JTable();
        bt_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/6476-verde.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);
        jcMousePanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("BALANCE DE CAJA");
        jcMousePanel1.add(jLabel2);
        jLabel2.setBounds(330, 20, 140, 20);

        tbl_balance_caja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "FECHA APERTURA", "MONTO APERTURA", "FECHA CIERRE", "MONTO CIERRE", "ESTADO DE CAJA"
            }
        ));
        jScrollPane1.setViewportView(tbl_balance_caja);

        jcMousePanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 740, 320);

        bt_salir.setText("CERRAR");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });
        jcMousePanel1.add(bt_salir);
        bt_salir.setBounds(320, 390, 120, 50);

        getContentPane().add(jcMousePanel1);
        jcMousePanel1.setBounds(0, 0, 820, 510);

        setBounds(0, 0, 796, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
         conexion.closeConnection();
        dispose();

    }//GEN-LAST:event_bt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reporte_balance_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reporte_balance_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reporte_balance_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reporte_balance_caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte_balance_caja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_salir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JTable tbl_balance_caja;
    // End of variables declaration//GEN-END:variables

    private void cargar_tabla() {
        DefaultTableModel tab = (DefaultTableModel) tbl_balance_caja.getModel();
        tab.setRowCount(0);
        try {
            st = Conexion.getInstanciaConexion().obtenerRutaConeccion().createStatement();
            rs = st.executeQuery("SELECT idapertura, fecha_apertura, monto_inicial, fecha_cierre, monto_cierre, estado\n"
                    + " FROM vista_apertura_cierre order by idapertura;");

            // Crea un nuevo SimpleDateFormat con el formato deseado
            SimpleDateFormat formatoDeseado = new SimpleDateFormat("dd/MM/yyyy");

            while (rs.next()) {
                // Obtiene la fecha de la base de datos
                Date fechaApertura = rs.getDate("fecha_apertura");
                Date fechaCierre = rs.getDate("fecha_cierre");

                // Formatea la fecha al nuevo formato
                String fechaAperturaStr = (fechaApertura != null) ? formatoDeseado.format(fechaApertura) : "";
                String fechaCierreStr = (fechaCierre != null) ? formatoDeseado.format(fechaCierre) : "";

                tab.addRow(new Object[]{
                    rs.getInt("idapertura"),
                    fechaAperturaStr,
                    rs.getInt("monto_inicial"),
                    fechaCierreStr,
                    rs.getInt("monto_cierre"),
                    rs.getString("estado"),});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar tabla" + e);
        }
    }

}
